server:
  port: 9001
spring:
  application:
    name: tensquare-base
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.83.128:3306/tensquare_base?characterEncoding=utf-8
    username: root
    data-password: 123456
  jpa:
    database: mysql
    show-sql: true